apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-pod-using-lpv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/www/html
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: claim
