apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: mongodb
  name: mongo-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongo-role
subjects:
- kind: ServiceAccount
  name: mongo
  namespace: mongodb