apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb
  namespace: mongodb
rules:
  - apiGroups: [""]
    resources: ["Pods","services","endpoints","persistentvolumeclaims"]
    verbs: ["get","list","watch","create","delete"]
  - apiGroups: ["apps"]
    resources: ["Statefulsets"]
    verbs: ["get","list","create","delete"]
