apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: testingg
spec:
  replicas: 3
  serviceName: mongo-svc
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.0.8
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "admin"
        command: ["mongod"]
        args: ["--replSet", "rs0", "--bind_ip_all"]
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: azurefile
      resources:
        requests:
          storage: 1Gi
