apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ak-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ak-utility
  template:
    metadata: 
      labels: 
        app: ak-utility
    spec: 
      containers:
        - name: ak-utility
          image: pavanelthepu/utility-api
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 25m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 400Mi

