apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.1"
            memory: "400Mi"
          limits:
            cpu: "1"
            memory: "600Mi"
        volumeMounts:
        - name: nginx-data
          mountPath: /var/www/html
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
          claimName: pvc

